services:
  fastapi:
    restart: unless-stopped
    build:
      context: .
      network: host
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./app:/app
    networks:
      - api_rest

  mariadb:
    image: mariadb:11
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - api_rest

volumes:
  mariadb_data:

networks:
  api_rest:
